sudo: false

language: node_js

node_js:
  - "6"
  - "6.1"
  - "5.11"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "cd src/"
  - "meteor npm install"

script: "npm run test:ci"